### PR TITLE
fix: external table definition parquet format options

### LINKED ISSUE #2146: Parquet format options are ignored during BQ table creation
It seems to me that during table creation bigquery client will ignore Parquet FormatOptions.

The issue is in the following code where [`ExternalTableDefinition` class is being turned into proto message](https://github.com/googleapis/java-bigquery/blob/main/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/ExternalTableDefinition.java#L303) ... as you can see, there is no code that checks for parquet format options (as opposed to AVRO, CSV and BIGTABLE format options). 

On the other hand, when the code is parsing a proto message to `ExternalTableDefinition`, the ParquetOptions are being correctly parsed - [see here](https://github.com/googleapis/java-bigquery/blob/main/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/ExternalTableDefinition.java#L481)

My expectation to solve this issue is following:
Something similar to the following should be added to ExternalTableDefinition#toExternalDataConfigurationPb
```java
    if (getFormatOptions() != null && FormatOptions.PARQUET.equals(getFormatOptions().getType())) {
      externalConfigurationPb.setParquetOptions(((ParquetOptions) getFormatOptions()).toPb());
    }
```

Do you think my assessment is correct and this is indeed a bug? Or have i missed something? Thank you

### PR DESCRIPTION
**Pull request by jbeluch**
Fixes #2146

### CODE REVIEW

**Comment by jbeluch** [comment]
Hi @Neenu1995 , is there an expected timeline for this type of change to be merged? Thanks.

**Review by Neenu1995 — APPROVED** [review]

**Comment by Neenu1995** [comment]
Tests fail:
```
java.lang.ClassCastException: com.google.cloud.bigquery.FormatOptions cannot be cast to com.google.cloud.bigquery.ParquetOptions
	at com.google.cloud.bigquery.ExternalTableDefinition.toExternalDataConfigurationPb(ExternalTableDefinition.java:315)
	at com.google.cloud.bigquery.ExternalTableDefinition.toPb(ExternalTableDefinition.java:283)
	at com.google.cloud.bigquery.TableInfo.toPb(TableInfo.java:511)
	at com.google.cloud.bigquery.BigQueryImpl.create(BigQueryImpl.java:290)
	at com.google.cloud.bigquery.it.ITBigQueryTest.testCreateExternalTableWithReferenceFileSchemaParquet(ITBigQueryTest.java:5175)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**Comment by jbeluch** [comment]
> Tests fail:
> 
> ```
> java.lang.ClassCastException: com.google.cloud.bigquery.FormatOptions cannot be cast to com.google.cloud.bigquery.ParquetOptions
> 	at com.google.cloud.bigquery.ExternalTableDefinition.toExternalDataConfigurationPb(ExternalTableDefinition.java:315)
> 	at com.google.cloud.bigquery.ExternalTableDefinition.toPb(ExternalTableDefinition.java:283)
> 	at com.google.cloud.bigquery.TableInfo.toPb(TableInfo.java:511)
> 	at com.google.cloud.bigquery.BigQueryImpl.create(BigQueryImpl.java:290)
> 	at com.google.cloud.bigquery.it.ITBigQueryTest.testCreateExternalTableWithReferenceFileSchemaParquet(ITBigQueryTest.java:5175)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> ```

thanks @Neenu1995, i missed running them the first time. ive made an additional fix so the IT test passes now. how should i handle squashing my commits? there was a bot commit on the branch so i didnt want to force push.

File: google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/FormatOptions.java [hunk 1]
```diff
@@ -106,8 +106,8 @@ public static FormatOptions googleSheets() {
   }
 
   /** Default options for PARQUET format. */
-  public static FormatOptions parquet() {
```
Comment (Neenu1995) [inline google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/FormatOptions.java:109]: Keep the return type as is.
Changing it will break existing customers.

Comment (jbeluch) [reply google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/FormatOptions.java:109]: changed.

should i handle squashing commits myself or is it done at merge time?

Comment (Neenu1995) [reply google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/FormatOptions.java:109]: Thanks @jbeluch. The commits should be updated now.
