### PR TITLE
fix: Socket-timeout at bigquery.it.ITNightlyBigQueryTest: testForTableNotFound

### LINKED ISSUE #2248: bigquery.it.ITNightlyBigQueryTest: testForTableNotFound failed
This test failed!

To configure my behavior, see [the Flaky Bot documentation](https://github.com/googleapis/repo-automation-bots/tree/main/packages/flakybot).

If I'm commenting on this issue too often, add the `flakybot: quiet` label and
I will stop commenting.

---

commit: bbbc4fe5f9da2ddcaaf70277ac0e6f8f37392ed7
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/552b6bfd-15b7-44fb-8239-f26483308b6c), [Sponge](http://sponge2/552b6bfd-15b7-44fb-8239-f26483308b6c)
status: failed
<details><summary>Test output</summary><br><pre>com.google.cloud.bigquery.BigQuerySQLException: Read timed out
	at com.google.cloud.bigquery.it.ITNightlyBigQueryTest.testForTableNotFound(ITNightlyBigQueryTest.java:518)
Caused by: com.google.cloud.bigquery.BigQueryException: Read timed out
	at com.google.cloud.bigquery.it.ITNightlyBigQueryTest.testForTableNotFound(ITNightlyBigQueryTest.java:518)
Caused by: java.net.SocketTimeoutException: Read timed out
	at com.google.cloud.bigquery.it.ITNightlyBigQueryTest.testForTableNotFound(ITNightlyBigQueryTest.java:518)
</pre></details>

### PR DESCRIPTION
**Pull request by prash-mi**
Defaulted timeoutMs to 10s & Added additional logging

Fixes #2248 ☕️

### CODE REVIEW

File: google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/ConnectionImpl.java [hunk 1]
```diff
@@ -190,11 +190,13 @@ public BigQueryResult executeSelect(String sql) throws BigQuerySQLException {
     try {
```
Comment (shollyman) [inline google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/ConnectionImpl.java:190]: May be better for another PR, but why is all this logic duplicated here, rather than just using a common executeSelect and not supplying the optional params/labels/etc?

**Review by shollyman — APPROVED** [review]
Approving this, though I recommend consolidating the execution logic in another PR if you don't do it in this one.

File: google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/ConnectionImpl.java (hunk 1 above)
Comment (prash-mi) [reply google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/ConnectionImpl.java:190]: Thanks for reviewing Seth, I have captured refactoring this as a task @ https://github.com/googleapis/java-bigquery/issues/2240 point#3 . Will update you once we raise a PR.
