### PR TITLE
fix: executeSelect now use provided credentials instead of GOOGLE_APP…

### LINKED ISSUE #2531: BigQueryStorage: Connection API uses GOOGLE_APPLICATION_CREDENTIALS instead of credentials configured on instance.
Thanks for stopping by to let us know something could be better!

#### Environment details

1. Specify the API at the beginning of the title. For example, "BigQuery: ...").
   General, Core, and Other are also allowed as types
2. OS type and version: Mac Ventura / Linux Ubuntu / 
3. Java version: 17 adoptium 
4.  version(s): 2.22.0 2.19.1

#### Steps to reproduce

  1. create client with non-default credentials.
  2. run query using  that takes longer than 10 seconds so that it falls out of the fast query pathway
  3. 💥 

#### Code: 
```java
// don't have the GOOGLE_APPLICATION_CREDENTIALS env variable set.
BigQueryCredentials credentials = ServiceAccountCredentials.fromStream(inStream)

BigQueryOptions bigQueryOptions = BigQueryOptions.newBuilder()
    .setProjectId(projectId)
    .setCredentials(credentials)
            .setLocation(region)
            .build()
Bigquery bigquery = bigQueryOptions.getService()
ConneptionSettings connectionSettings = ConnectionSettings.newBuilder()
       .setUseReadAPI(false)
       .setRequestTimeout(10L)
       .setMaxResults(100L)
       .setUseQueryCache(true)
       .build();
Connection connection = bigquery.createConnection(connectionSettings);
String selectQuery = "<query that takes a little while and moves past the initial jobs.query timeout";
ListenableFuture<ExecuteSelectResponse> executeSelectFuture = connection.executeSelectAsync(selectQuery, ...);
```

#### Stack trace
```
The Application Default Credentials are not available. They are available if running in Google Compute Engine. Otherwise, the environment variable GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file defining the credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
```

#### External references such as API reference guides

If the highThroughPut read path is hit, a BigQueryReadClient is created using the default `BigQueryReadClient.create()` method. [here](https://github.com/googleapis/java-bigquery/blob/v2.22.0/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/ConnectionImpl.java#L951). 

Because no credentials are passed, this looks for the `GOOGLE_APPLICATION_CREDENTIALS` instead of passing along the credentials that are configured for the bigquery client being used by the Connection.

### PR DESCRIPTION
**Pull request by PhongChuong**
…LICATION_CREDENTIALS

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/java-bigquery/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

Fixes #2531, #2234 ☕️

### CODE REVIEW

File: google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/ConnectionImpl.java [hunk 1]
```diff
@@ -955,7 +957,12 @@ BigQueryResult highThroughPutRead(
 
     try {
       if (bqReadClient == null) { // if the read client isn't already initialized. Not thread safe.
-        bqReadClient = BigQueryReadClient.create();
+        BigQueryReadSettings settings =
+            BigQueryReadSettings.newBuilder()
+                .setCredentialsProvider(
+                    FixedCredentialsProvider.create(bigQueryOptions.getCredentials()))
```
Comment (shollyman) [inline google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/ConnectionImpl.java:963]: Is the FixedCredentialsProvider indirection needed, or can we set the retrieved credentials directly?  Is this a typing issue, or does the indirection get us some other benefit?

**Review by shollyman — APPROVED** [review]
one minor question about how the credentials are propagated, otherwise LGTM

**Comment by PhongChuong** [comment]
Thanks for the review.
