### PR TITLE
fix: Add labels to converter for listTables method (#3735)

### LINKED ISSUE #3735: listTables method doesn't pass table labels
Hello, 

I noticed that `java-bigquery` library does not pass-through labels from the rest API list table method. We need to read `labels` in our project, without that we need to fetch details for each table, which causes many problems, while all required data is available but just not converted. 

The problem I debugged is in the method `listTablesSkipExceptionTranslation` where there is no conversion of labels.

Look at the breakpoint in the debug mode:

Image

I will attach Pull Request to add labels.

### PR DESCRIPTION
**Pull request by tloszabno**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/java-bigquery/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #3735  ☕️

If you write sample code, please follow the [samples format](
https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/SAMPLE_FORMAT.md).

### CODE REVIEW

File: google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/BigQueryImplTest.java [hunk 1]
```diff
@@ -155,6 +155,9 @@ public class BigQueryImplTest {
       TableInfo.of(TABLE_ID, TABLE_DEFINITION_WITH_RANGE_PARTITIONING);
   private static final TableInfo TABLE_INFO = TableInfo.of(TABLE_ID, TABLE_DEFINITION);
   private static final TableInfo OTHER_TABLE_INFO = TableInfo.of(OTHER_TABLE_ID, TABLE_DEFINITION);
+  private static final TableInfo OTHER_TABLE_WITH_LABELS_INFO = TableInfo.newBuilder(OTHER_TABLE_ID, TABLE_DEFINITION)
+      .setLabels(ImmutableMap.of("key", "value"))
```
Comment (PhongChuong) [inline google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/BigQueryImplTest.java:159]: Nit. move ImmutableMap.of("key", "value") to static final var and use it in the validation. I.e.,
```
  private static final ImmutableMap<String, String> TABLE_LABELS = ImmutableMap.of("key", "value");
...
  private static final TableInfo OTHER_TABLE_WITH_LABELS_INFO = TableInfo.newBuilder(OTHER_TABLE_ID, TABLE_DEFINITION)
      .setLabels(TABLE_LABELS)
      .build();
...
    assertEquals(TABLE_LABELS, page.getValues().iterator().next().getLabels());
```

**Review by PhongChuong — COMMENTED** [review]
PR looks good.
Just a minor change suggested for the unit test.
Thanks for creating a fix.

File: google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/BigQueryImplTest.java (hunk 1 above)
Comment (tloszabno) [reply google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/BigQueryImplTest.java]: Hello @PhongChuong 
Thank you for the review. 
Suggestion applied.

**Review by PhongChuong — APPROVED** [review]

**Comment by PhongChuong** [comment]
Thank you for the fix.

**Comment by tloszabno** [comment]
@PhongChuong can you trigger a release for that fix https://github.com/googleapis/java-bigquery/pull/3739? 
Or if the rules for release are different, when do you predict the release could happen? 
Thanks
