### PR TITLE
fix: schema and totalRows for duplicate request ids

### LINKED ISSUE #802: Fast query path not handling multiple query runs correctly
Below test case fails:
``` 
  @Test
  public void testFastQueryDuplicateRequestIds() throws InterruptedException {
    String query =
        "SELECT TimestampField, StringField, BooleanField FROM " + TABLE_ID_FASTQUERY.getTable();
    QueryJobConfiguration config =
        QueryJobConfiguration.newBuilder(query).setDefaultDataset(DatasetId.of(DATASET)).build();
    TableResult result = bigquery.query(config);
    assertEquals(QUERY_RESULT_SCHEMA, result.getSchema());
    assertEquals(2, result.getTotalRows());
    assertNull(result.getNextPage());
    assertNull(result.getNextPageToken());
    assertFalse(result.hasNextPage());

    config.toBuilder().setQuery(query).build();
    TableResult result2 = bigquery.query(config);
    assertEquals(QUERY_RESULT_SCHEMA, result2.getSchema());
    assertEquals(2, result2.getTotalRows());
    assertNull(result2.getNextPage());
    assertNull(result2.getNextPageToken());
    assertFalse(result2.hasNextPage());
  }
```

### PR DESCRIPTION
**Pull request by pmakani**
Fixes #802

### CODE REVIEW

**Review by stephaniewang526 — APPROVED** [review]

File: google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryImpl.java [hunk 1]
```diff
@@ -1265,14 +1266,22 @@ private TableResult queryRpc(
...
+    long numRows;
+    Schema schema;
+    if (results.getSchema() == null && results.getJobComplete()) {
+      JobId jobId = JobId.fromPb(results.getJobReference());
+      Job job = getJob(jobId, options);
+      TableResult tableResult = job.getQueryResults();
+      return tableResult;
     } else {
-      numRows = results.getTotalRows().longValue();
+      schema = Schema.fromPb(results.getSchema());
```
Comment (epavan123) [inline google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryImpl.java:1277]: results.getSchema() can still be null here..

Comment (pmakani) [reply google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryImpl.java]: @epavan123 Done
