### PR TITLE
test: fix flaky IT testExecuteSelectWithCredentials

### LINKED ISSUE #3471: bigquery.it.ITBigQueryTest: testExecuteSelectWithCredentials failed
This test failed!

To configure my behavior, see [the Flaky Bot documentation](https://github.com/googleapis/repo-automation-bots/tree/main/packages/flakybot).

If I'm commenting on this issue too often, add the `flakybot: quiet` label and
I will stop commenting.

---

commit: 08b28c510a2280119a03da3caa385ec31e0c944c
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/e741e9d9-a4d5-4965-9215-1dda9cbfaf81), [Sponge](http://sponge2/e741e9d9-a4d5-4965-9215-1dda9cbfaf81)
status: failed

### PR DESCRIPTION
**Pull request by PhongChuong**
Use priority instead of job timeout to force non-fast query in executeSelect.

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/java-bigquery/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

Fixes #3471 ☕️

### CODE REVIEW

File: google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java [hunk 1]
```diff
@@ -3272,7 +3271,7 @@ public void testExecuteSelectWithCredentials() throws SQLException {
 
     ConnectionSettings connectionSettings =
         ConnectionSettings.newBuilder()
-            .setJobTimeoutMs(10L) //  Force non-fast query to use BigQueryReadClient.
+            .setPriority(Priority.INTERACTIVE) //  Force non-fast query to use BigQueryReadClient.
```
Comment (shollyman) [inline google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java:3274]: How/why would this force read client?  Interactive is the default priority already.

Comment (PhongChuong) [reply google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java:3274]: We check a few criteria in the ConnectionSettings to determine if fast query should be used in:
https://github.com/googleapis/java-bigquery/blob/8f2e5c542760ecd7c217c36c80cb3b5aebee6a73/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/ConnectionImpl.java#L1209
This forces the check to fail and executeSelect to use the non fast query path:
https://github.com/googleapis/java-bigquery/blob/8f2e5c542760ecd7c217c36c80cb3b5aebee6a73/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/ConnectionImpl.java#L245C1-L246C1

Comment (shollyman) [reply google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/it/ITBigQueryTest.java:3274]: Thanks for the clarification!

**Review by shollyman — APPROVED** [review]

**Comment by PhongChuong** [comment]
Thanks for the review.
